### ISSUE TITLE
Support function returning IntervalBox and only use them internally

### ISSUE THREAD

**Issue by Kolaru** [JuliaIntervals/IntervalRootFinding.jl#107]
Currently, the functions passed to `roots` must return `SVector` which has several drawbacks:

- Require one more explicit import from the user.
- `IntervalBox` and `SVector` work in a quite similar manner, but are not equivalent, which may cause unexpected bugs. For example consider the following

```jl
IB = IntervalBox(emptyinterval(), emptyinterval())
SV = SVector(emptyinterval(), emptyinterval())
```

Here `isempty(IB)` evaluates to `true` while `isempty(SV)` evaluates to `false`. This caused some of the bugs I'm trying to fix in #93 (an update is coming soon).

Therefore, I advise that `SVector` should only be used when `ForwardDiff` is directly involved, i.e. deep inside the contractors.

It may be possible to support both the current behavior and function returning `IntervalBox` (converting to the latter internally) using fancy multiple dispatch, otherwise this would be a breaking change.

**Comment by dpsanders** [comment]
Good point and good idea.

For `ForwardDiff` I think we just need
```
import ForwardDiff

ForwardDiff.gradient(f, X::IntervalBox) = ForwardDiff.gradient(f, X.v)
ForwardDiff.jacobian(f, X::IntervalBox) = ForwardDiff.jacobian(f, X.v)
ForwardDiff.hessian(f, X::IntervalBox) = ForwardDiff.hessian(f, X.v)
```
