### ISSUE TITLE
Make a RootProblem type

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalRootFinding.jl#109]
It may be useful to have a `RootProblem` type that encodes the function, the `IntervalBox`, the dimension, etc.

**Comment by dpsanders** [comment]
Here's a possible definition for a type to wrap a function:
```
"""
Type representing a function to be used in a branch and bound algorithm
"""

struct BranchAndBoundFunction{F,N,T}
    f::F
    X::IntervalBox{N,T}
    input_dim::Int
    output_dim::Int
    
    function BranchAndBoundFunction(f::F, X::IntervalBox{N,T}) where {F<:Function,N,T}
        new{F,N,T}(f, X, N, length(f(X)))
    end
end

(f::BranchAndBoundFunction{F,N,T})(X::IntervalBox{N,T}) where {F,N,T} = f.f(X)
```

**Comment by Kolaru** [comment]
Now available as `RootProblem`. The object  can be iterated to get the result and uses the exact same signature as `roots`.

The iterated value is a bit confusing still and could do with a bit more documentation and polishing.
