### ISSUE TITLE
No method roots(f, v::Vector{IntervalBox})

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalRootFinding.jl#117]
I'm sure this used to work.

**Comment by dpsanders** [comment]
Maybe it didn't. But it should.

**Comment by yashcodes** [comment]
`function _roots(f, X::Region, contractor::Type{C},
               strategy::Type{S}, tol::Float64) where {C <: Contractor, S <: BBSearch}`

**Comment by Kolaru** [comment]
Fixed on master with the removal of `IntervalBox`.
