### ISSUE TITLE
Factor out branch and bound into new package

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalRootFinding.jl#130]
It would be very useful to factor out `branch_and_bound.jl` into a new package.

But we need to watch for performance: anecdotally, I'm seeing quite a big slow down for large problems with the new tree structure?

**Comment by Kolaru** [comment]
I should be able to look into this shortly.

Do you have any example for the slow down? Hopefully there is a nice and easy fix for it.

**Comment by Kolaru** [comment]
So here it is, if you want to have a look:

https://github.com/Kolaru/BranchAndPrune.jl

Some notes:

- I still need to do the stuff to add it to the general registry
- Nothing fancy like coverall or such has been setup yet
- I have named it `BranchAndPrune.jl` as `BranchAndBound.jl` is already taken and this one does not actually do any bounding
- Several types have been renamed too

Once it's registered I'll make a PR to use it as a dependency.

**Comment by dpsanders** [comment]
Fantastic, thanks a lot!
