### ISSUE TITLE
Tag v0.4.1

### ISSUE THREAD

**Issue by lbenet** [JuliaIntervals/IntervalRootFinding.jl#138]

**Comment by dpsanders** [comment]
This should be done by TagBot

**Comment by dpsanders** [comment]
You can just do `@JuliaRegistrator register` on the last commit

**Comment by dpsanders** [comment]
OK apparently I did it here.

**Comment by lbenet** [comment]
Ok... always forget it...

I was about asking where have you done it :-)

**Comment by lbenet** [comment]
Incidentally, this was needed to make some updates in TaylorModels.

**Comment by lbenet** [comment]
I didn't know about about these requirements to have an automatic merge... We'll have to wait ~24 hrs.

**Comment by dpsanders** [comment]
Just change it to `julia = "1"` I think.

**Comment by lbenet** [comment]
That may solve part of the issue, but not 

> - A patch release is not allowed to narrow the supported range of Julia versions

**Comment by dpsanders** [comment]
Wasn't the supported range already 1.0 and above?

**Comment by lbenet** [comment]
No. I had to create the `Project.toml` itself. Perhaps the problem is the `≥` in that line, which I overlooked, and which is perhaps better to have as `^1.0.0`.

By the way, we will eventually need to update a bunch of things to julia `^1.1.0`, since that's a requirement in `IntervalArithmetics.jl` (whose Project.toml needs also to be updated).

**Comment by lbenet** [comment]
I noticed you changed that line of `julia`, and seems to have solved part of the issue. Should we tag v0.5.0 instead, to satisfy the requirements for automatic merging?

**Comment by dpsanders** [comment]
Yes let's do that. And may as well change it to Julia 1.1 while doing so.

**Comment by lbenet** [comment]
Can you do it?

**Comment by lbenet** [comment]
Incidentally, maybe it is a good time to have `Polynomials = "^0.5.0"`, instead of having v0.5.0 fixed...

**Comment by lbenet** [comment]
Addressed in https://github.com/JuliaIntervals/IntervalRootFinding.jl/commit/21be6924ec971ccc0c61a5f1e171f3b8f35c42c2
