### ISSUE TITLE
Throw an error when input and output dimension mismatch

### ISSUE THREAD

**Issue by Kolaru** [JuliaIntervals/IntervalRootFinding.jl#150]
As found in #148, Newton and Krawczyck should explicitly check that the input and output dimension of the function are the same, as otherwise the methods do not work and they should not fail silently.

**Comment by OlivierHnt** [comment]
Is this issue resolved on master?

**Comment by Kolaru** [comment]
Yes

```julia
julia> function f(xy)
           x, y = xy
           [x^2 - 2]
       end
f (generic function with 1 method)

julia> roots(f, x)
ERROR: DimensionMismatch: matrix is not square: dimensions are (1, 2)
```

I leave the issue open for now. I will make a PR with tests for all issues resolved by chance.
