### ISSUE TITLE
Graceful handling of infinity

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalRootFinding.jl#161]
Currently the following hangs in an infinite calculation:
```jl

julia> using IntervalArithmetic, IntervalRootFinding

julia> roots(x -> x^2 - x, -Inf..Inf)
````
since it cannot prove that it can exclude the regions at infinity.

We should explicitly check for infinite intervals and stop bisecting at some point, say when the result is above `1e200`.

**Comment by KronosTheLate** [comment]
I don't have anything to contribute with in terms of solutions, but as a user, being able to check from -Inf to Inf is what I actually want to do most of the time, and so this would be a great feature.

**Comment by OlivierHnt** [comment]
For the record, the current behaviour gives the following

```Julia
julia> roots(x -> x^2 - x, -Inf..Inf)
4-element Vector{Root{Interval{Float64}}}:
 Root([-1.28998e-14, 1.22107e-14]_dac_NG, :unique)
 Root([0.999999, 1.00001]_dac_NG, :unique)
 Root([1.79769e+308, 1.7977e+308]_dac_NG, :unknown)
 Root([1.79769e+308, 1.7977e+308]_dac_NG, :unknown)
```

which seems fair. However, there is a discrepancy with `BigFloat` since

```Julia
roots(x -> x^2 - x, big(-Inf..Inf))
```

hangs...

**Comment by Kolaru** [comment]
Well, since we are going to the last representable number, it may take some time for `BigFloat`

```julia
julia> prevfloat(typemax(Float64))
1.7976931348623157e308

julia> prevfloat(typemax(BigFloat))
5.875653789111587590936911998878442589938516392745498308333779606469323584389875e+1388255822130839282
```

I am tempted to say that this is a user issue, as the maximum number of iteration can now be set

```julia
julia> roots(x -> x^2 - x, big(-Inf..Inf) ; max_iteration = 1000000)
3-element Vector{Root{Interval{BigFloat}}}:
 Root([5.87565e+1388255822130839282, 5.87566e+1388255822130839282]₂₅₆_dac_NG, :unknown)
 Root([5.87565e+1388255822130839282, 5.87566e+1388255822130839282]₂₅₆_dac_NG, :unknown)
 Root([-2.84502e+1388255822130688854, 8.65093e+1388255822130688854]₂₅₆_dac, :unknown)
```

Of course, `big(Inf)` is so big that it's not very informative... we would need a logarithmic-like bisection scheme to handle that gracefully I would say.

**Comment by OlivierHnt** [comment]
Yes, I agree, I think this can be closed then.
