### ISSUE TITLE
Acces to elements / sort

### ISSUE THREAD

**Issue by ChrisNabold** [JuliaIntervals/IntervalRootFinding.jl#174]
I solved a problem and IntervalRootfinding finds the followin roots:14-element Vector{Root{Interval{Float64}}}:
 Root([4.71238, 4.71239], :unknown)
 Root([0, 5.53002e-08], :unknown)
 Root([7.85398, 7.85399], :unknown)
 Root([14.1371, 14.1372], :unknown)
 Root([17.2787, 17.2788], :unknown)
 Root([17.2207, 17.2208], :unique)
 Root([14.0661, 14.0662], :unique)
 Root([2.43045e-07, 2.97808e-07], :unknown)
 Root([1.20573e-07, 1.47846e-07], :unknown)
 Root([10.9955, 10.9956], :unknown)
 Root([1.57079, 1.5708], :unknown)
 Root([7.72525, 7.72526], :unique)
 Root([10.9041, 10.9042], :unique)
 Root([4.4934, 4.49341], :unique)
I would like to select only elements with the identifier :unique
how can I transform the results into an array eg  sol = [4.71238, 0.5, 7.85398 ....]?
Thank you for your help

**Comment by lucaferranti** [comment]
Hi,

you can use the function `isunique` to filter the roots with identifier `:unique`, e.g.

```julia
julia> rts = roots(x -> x^2*(x-1)*(x-2), -10..10)
3-element Vector{Root{Interval{Float64}}}:
 Root([0.999999, 1.00001], :unique)
 Root([1.99999, 2.00001], :unique)
 Root([-5.98024e-08, 1.01296e-08], :unknown)

julia> sol = filter(isunique, rts)
2-element Vector{Root{Interval{Float64}}}:
 Root([0.999999, 1.00001], :unique)
 Root([1.99999, 2.00001], :unique)
```

From that, you can use the function `interval` to extract the intervals from the objects of type `Root`

```julia
julia> interval.(sol)
2-element Vector{Interval{Float64}}:
 [0.999999, 1.00001]
 [1.99999, 2.00001]
```

so combining the two before you can do
```julia
julia> rts = roots(x -> x^2*(x-1)*(x-2), -10..10)
3-element Vector{Root{Interval{Float64}}}:
 Root([0.999999, 1.00001], :unique)
 Root([1.99999, 2.00001], :unique)
 Root([-5.98024e-08, 1.01296e-08], :unknown)

julia> sol = interval.(filter(isunique, rts))
2-element Vector{Interval{Float64}}:
 [0.999999, 1.00001]
 [1.99999, 2.00001]
```

**Comment by ChrisNabold** [comment]
Hi Luca,

 

Thank you – you solved my problem!

Regards,

Chris Nabold
