### ISSUE TITLE
Update to make compatible with IntervalArithmetic master

### ISSUE THREAD

**Issue by Kolaru** [JuliaIntervals/IntervalRootFinding.jl#191]
IntervalArithmetic.jl is moving toward v1.0 with many breaking change. We need to update this package accordingly.

**Comment by OlivierHnt** [comment]
Also for compatibility with v0.21, see the PR #192

**Comment by PhyX-Meow** [comment]
Any progress of this?

**Comment by Kolaru** [comment]
I'm working on it ;). Current progress is on the IA_v022 branch, I hope to have it done early january.
