### ISSUE TITLE
Doc badge does not point to the package doc

### ISSUE THREAD

**Issue by Kolaru** [JuliaIntervals/IntervalRootFinding.jl#193]
The doc badge leads to the JuliaInterval website, that doesn't itself lead the doc deployed from the `doc/` folder, that is here instead https://juliaintervals.github.io/IntervalRootFinding.jl/latest/.

@lucaferranti

**Comment by lucaferranti** [comment]
side note, it's actually not being deployed atm I think: https://github.com/JuliaIntervals/IntervalRootFinding.jl/blob/master/.github/workflows/CI.yml ? latest commit on gh-pages branch is from January 2021.

At least it points to the website `IntervalRootFinding` webpage: https://juliaintervals.github.io/pages/packages/intervalrootfinding/#related_content which does have some documentation.

I do agree it would be a huge pain in the *** to maintain documentation in a separate website, so probably we should switch back to documenter.

When we started the website, we had less tools, but now I think would be very cool to rewrite the website with [MultiDocumenter.jl](https://github.com/JuliaComputing/MultiDocumenter.jl) for the homepage (see e.g. [SciML docs](https://docs.sciml.ai/Overview/stable/). This would be a nice balance of having one website while the docs deployed from every package.

**Comment by lucaferranti** [comment]
so actions would be (for now)

- [ ] reinsert workflow to deploy docs from Documenter
- [ ] update badge

I can do this tomorrow morning
