### ISSUE TITLE
Where are docs for 0.6 / what are all the breaking changes?

### ISSUE THREAD

**Issue by Datseris** [JuliaIntervals/IntervalRootFinding.jl#207]
I am trying to update CHaosTools.jl to the new breaking release. I am running into problems with using a `Vector` of `Interval`: https://github.com/JuliaDynamics/ChaosTools.jl/actions/runs/11868975864/job/33078794485?pr=338#step:7:680 

The breaking change release notes says "remove `IntervalBox`, just use `Vector{Interval}`" but that does not work for the `roots` function. There aren't updated docs online yet to check what's the correct usage.

**Comment by Datseris** [comment]
If you can provide any help with https://github.com/JuliaDynamics/ChaosTools.jl/pull/338 I would appreciate it because I thought I followed the breaking changes correctly :(

**Comment by Datseris** [comment]
Right, I found the breaking changes now: https://github.com/JuliaIntervals/IntervalRootFinding.jl/blob/master/NEWS.md , so it was wrong to look at https://github.com/JuliaIntervals/IntervalRootFinding.jl/releases/tag/v0.6.0

**Comment by Datseris** [comment]
Right I fixed many things, now my problem is that I have no idea in what format the Jacobian (derivative) needs to be specified in, because this simple one doesn't work:

```julia
    henon_rule(x) = SVector{2}(1.0 - p[1]*x[1]^2 + x[2], p[2]*x[1])
    henon_jacob(x) = SMatrix{2,2}(-2*p[1]*x[1], p[2], 1.0, 0.0)
```

Can someone tell me perhaps what's the new format?

**Comment by Kolaru** [comment]
Thanks for reporting ! I have added a badge in the README pointing to the `master` doc, and a note there about not mixing vector types.

**Comment by Datseris** [comment]
The `dev` docs are here: https://juliaintervals.github.io/IntervalRootFinding.jl/dev/#Stationary-points   . I assume this is what you mean by `master` doc? These docs are outdated, in the example I link above they use the old signature. Are these the updated docs and just the home page is out of date?
