### ISSUE TITLE
Tolerance in Newton is not respected

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalRootFinding.jl#36]
The tolerance setting doesn't seem to be respected by Newton.

**Comment by dpsanders** [comment]
It's hard-coded in the `refine` function :/

**Comment by eeshan9815** [comment]
@dpsanders What should be the expected behaviour? If `tolerance` is reached before `NX == X` `break`s the loop, return it with a `:unknown` flag?

**Comment by dpsanders** [comment]
Yes, I think if `tolerance` is reached before it finds a unique root, then break and return `:unknown`.

**Comment by dpsanders** [comment]
Fixed by #55.
