### ISSUE TITLE
Move lexcmp on Intervals to IntervalArithmetic.jl

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalRootFinding.jl#4]

**Comment by eeshan9815** [comment]
@dpsanders For two intervals, would the lexicographically smaller interval be the one which has a smaller `a.lo`? And then `a.hi` if same?

**Comment by dpsanders** [comment]
Yes but I think this is no longer used.
Most of the stuff in bisection.jl and Newton.jl is obsolete and should be
removed.

The only function of interest now is roots and the stuff mainly in
branchandprune.jl.

The N operator needs to be salvaged from Newton.jl

**Comment by Kolaru** [comment]
The function seems to have been dealt with.
