### ISSUE TITLE
Remove old code

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalRootFinding.jl#41]
Remove old code:
- [x] bisection.jl
- [x] move out definitions of `N` used in `branch_and_prune`

- [ ] krawczyk.jl  
- [ ] newton.jl
- [ ] find_roots stuff

**Comment by Kolaru** [comment]
Is the code in `newton1d.jl` still considered maintained and part of the current API ?

**Comment by dpsanders** [comment]
That was added in last year's GSoC project.

In a way it's useful to have a separate code, but the actual code itself is long and convoluted. We should see if anything is salvagable and probably get rid of the rest.

cc @eeshan9815

**Comment by eeshan9815** [comment]
If I recall correctly, it worked well for complicated functions, and functions which had a lot of multiple roots, where the existing solver sometimes struggled. So, should it be implemented as a part of the `roots` interface and kept as a different keyword solver?
