### ISSUE TITLE
Add hard test cases

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalRootFinding.jl#44]
There are some nice ones in

https://www.sciencedirect.com/science/article/pii/S0377042700007111

with results we can compare with.

**Comment by gwater** [comment]
For your information: I'm preparing a pull request with implementations of some examples from Smiley and Chun's article. So far, all examples pass (with the Newton contractor) although some (specifically Example 5.5) take upwards of 30 minutes on my machine.

**Comment by dpsanders** [comment]
Great, thanks!

**Comment by dpsanders** [comment]
Done in #70.
