### ISSUE TITLE
Implement Krawczyk in N dimensions

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalRootFinding.jl#46]

**Comment by Kolaru** [comment]
I am working on this (just to let you know and avoid doing it twice independently).

**Comment by dpsanders** [comment]
Thanks!

**Comment by dpsanders** [comment]
By the way, it was announced today that @eeshan9815 will be working on this package as part of GSoC!

In particular, one of his first jobs will be to implement Gauss-Seidel / Hansen-Sengupta.
So let's leave that for him to do, please.

**Comment by dpsanders** [comment]
Krawczyk in N dimensions seems to be working now?

**Comment by Kolaru** [comment]
Except for bugs reported in other issues, yes.

**Comment by dpsanders** [comment]
Thanks!
