### ISSUE TITLE
Remove NewtonContractor

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalRootFinding.jl#53]
I believe we can remove NewtonContractor by just using

`roots(f, f_prime, Newton)`

Am I incorrect, @Kolaru?

**Comment by dpsanders** [comment]
Or prob better using a keyword arg:

`roots(f, Newton; deriv=f_prime)`

**Comment by Kolaru** [comment]
Yes, that perfectly correct.

**Comment by dpsanders** [comment]
Fixed by #55.
