### ISSUE TITLE
Example 5.5 from Smiley and Chun (2001) solved inconsistently

### ISSUE THREAD

**Issue by gwater** [JuliaIntervals/IntervalRootFinding.jl#86]
The example in `test/smiley_examples.jl` has 41 roots, however, only 20 are found on some setups. On other setups all 41 are identified correctly. This inconsistency was first discovered and discussed in #70.

**Comment by gwater** [comment]
Some progress on triangulating the issue: On my machine the example works with v0.7.0 of [StaticArrays.jl](https://github.com/JuliaArrays/StaticArrays.jl) and breaks with v0.7.2.

**Comment by gwater** [comment]
The example is already broken with v0.7.1 of StaticArrays.jl

**Comment by gwater** [comment]
git bisection indicates that the problem is related to [this commit](https://github.com/JuliaArrays/StaticArrays.jl/commit/9b6427fd630b0636ce66281fb86f54493e6ba1d1) in StaticArrays.jl

**Comment by dpsanders** [comment]
Great detective work, thanks. Would you like to report it at StaticArrays.jl?

**Comment by gwater** [comment]
Sure, it cannot hurt to have them take a look at it. The code in question is called [here](https://github.com/JuliaIntervals/IntervalRootFinding.jl/blob/v0.2.1/src/contractors.jl#L109), correct?

**Comment by dpsanders** [comment]
Yes, that's the right place.

**Comment by gwater** [comment]
Given that the next version of StaticArrays will most likely contain a fix for this issue, I think v0.7.1 through v0.7.2 of StaticArrays.jl should be blacklisted in IntervalArithmetic.jl's and IntervalRootFinding.jl's `REQUIRE` to protect users from incorrect results.

**Comment by gwater** [comment]
The discussion in the StaticArrays issue raised questions about the definition of `isinf(::Interval)`. Looking at its [current definition ](https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/1114b4c2f1ca22a5f5b0074c9db2a7b77b0af069/src/intervals/special.jl#L25) I'm concerned, too:
```
isentire(x::Interval) = x.lo == -Inf && x.hi == Inf
isinf(x::Interval) = isentire(x)
```
This definition seems both geneerous and too specific at the same time. My understanding is that the question "Is this number infinite?" cannot be answered at all for an interval that contains both an infinity and finite numbers. It could be both finite or infinite, and we don't know yet.

Should I open an issue to discuss this further?

**Comment by dpsanders** [comment]
Yes, I agree. Please do open an issue, yes.

**Comment by dpsanders** [comment]
I think the solution for us is to use the work in #67.
cc @eeshan9815

**Comment by gwater** [comment]
Yes, it makes sense to have a safe implementation of left divide within the package since that operation is so crucial to the Newton method.

**Comment by eeshan9815** [comment]
So should the methods in #67 be used instead of `Base.\` by importing and modifying it?

**Comment by dpsanders** [comment]
Yes, that's probably a good solution. Let's try it.

**Comment by dpsanders** [comment]
Maybe make it do Gaussian elimination for now.
But probably there should be a way to choose in the `roots` function which type of linear solution to use.

**Comment by eeshan9815** [comment]
Should it use the preconditioned version or the normal one?

**Comment by dpsanders** [comment]
There should be an option to either use it or not, and test both to see which is better!

**Comment by dpsanders** [comment]
I think this will be solved by using interval Gauss-Seidel instead of Gaussian elimination to solve the linear system. @Kolaru is it possible to specify this option?

**Comment by dpsanders** [comment]
Note that I was also using the `fastpowers` branch of `IntervalArithmetic.jl`; without that, any calculation involving interval powers will be an order of magnitude slower.

**Comment by Kolaru** [comment]
@dpsanders Currently it's not possible, the contractors using the `\` operator (and thus whatever it is bind to).

I've added it to the list in #116 of what should be possible to pass to `roots`.

**Comment by gwater** [comment]
Silent failure should be solved by JuliaIntervals/IntervalArithmetic.jl#571
