### ISSUE TITLE
Return semi-infinite intervals when cannot guarantee roots

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/IntervalRootFinding.jl#96]
e.g. for f(x) = (x-1)*x*(x+1) on (-Inf..Inf).

**Comment by Kolaru** [comment]
Why can't the roots be guaranteed here ?

**Comment by dpsanders** [comment]
My bad, they apparently can. There are some functions for which it is not possible to exclude "roots at infinity".

**Comment by dpsanders** [comment]
Ouch. Exactly!

**Comment by dpsanders** [comment]
Even with bisection this fails. I think this is because we keep bisecting intervals even when they are atomic. This needs to be fixed.

**Comment by dpsanders** [comment]
Currently we get
```
julia> roots(x -> 1/x, 1..∞)
Root([1.79769e+308, ∞], :unique)
```
The `unique` here is wrong -- maybe Newton is not checking strict inclusion?

Krawczyk just hangs.

An example of not being able to guarantee roots is

```
julia> roots(x -> x^2 - 2x, -Inf..Inf)
```
When `x` is a semi-infinite interval, `x^2 - 2x` always gives `-Inf..Inf` and nothing can be done, 
even though for any finite, large interval it can immediately prove that there is no 0.

**Comment by Kolaru** [comment]
Currently this creates an `:unknown` root with `dac` decoration that gets bisected forever, which is a separate issue (#178).
